
function bc(p){return p>85?'r':p>60?'y':'g'}
function el(s){if(!s)return'--';const d=new Date(s),n=new Date(),t=Math.max(0,Math.floor((n-d)/1e3)),m=Math.floor(t/60),s2=t%60,h=Math.floor(m/60),m2=m%60;return h?h+'h '+m2+'m '+s2+'s':m?m+'m '+s2+'s':s2+'s'}
function sb(id,p,c){const e=document.getElementById(id);if(e){e.style.width=Math.min(100,Math.max(0,p))+'%';if(c)e.className='bf '+c}}
function esc(s){if(s==null)return'';const d=document.createElement('div');d.textContent=String(s);return d.innerHTML}
function S(s,n){return s?String(s).substring(0,n):''}
function $(id){return document.getElementById(id)}

async function R(){
 let d;try{const r=await fetch('/api/state');d=await r.json()}catch(e){$('refresh').textContent='FETCH ERR: '+e.message;return}
 const p=d.progress||{},o=p.overall||{},st=o.status||'idle',pct=o.percent||0;
 const td=d.todo||{},ts=td.stats||{};const br=d.blocker_resolution||{};const etas=d.etas||{};const stages=p.stages||[];const ui=d.ui_flags||{};
 let ok=0,fail=0;
 try{$('governance-card').style.display=ui.governance_panel?'block':'none';$('executive-card').style.display=ui.executive_conflict?'block':'none';ok++}catch(e){fail++;console.error('flags',e)}
 // --- Completion Tracker ---
 try{const c=d.completion||{};
  $('ct-bar').style.width=(c.overall_percent||0)+'%';
  $('ct-pct').textContent=(c.overall_percent||0).toFixed(1)+'%';
  $('ct-done').textContent=c.done_tasks||0;$('ct-total').textContent=c.total_tasks||0;
  $('ct-eta-pipe').textContent='Pipeline: '+(c.pipeline_eta||'--');
  $('ct-eta-todo').textContent='All tasks: '+(c.todo_eta||'--');
  const rs2=c.roi_score||0;
  $('ct-roi-score').textContent='Maximum ROI: '+rs2+'%';
  $('ct-roi-score').style.color=rs2>=80?'var(--green)':rs2>=50?'var(--yellow)':'var(--red)';
  // Phase bars
  let phH='';(c.phases||[]).forEach(ph=>{
    const pc=ph.percent||0;const col=pc>=80?'var(--green)':pc>=40?'var(--blue)':'var(--dim)';
    phH+='<div style="background:var(--bg);border:1px solid var(--border);border-radius:4px;padding:6px"><div style="font-size:10px;color:var(--dim)">'+esc(ph.name)+'</div><div class="bar" style="height:10px;margin:4px 0"><div class="bf" style="width:'+pc+'%;background:'+col+';height:100%;border-radius:3px"></div></div><div style="font-size:11px;display:flex;justify-content:space-between"><span>'+pc.toFixed(0)+'%</span><span style="color:var(--dim)">'+ph.done+'/'+ph.total+'</span></div></div>';
  });$('ct-phases').innerHTML=phH;
  // Blockers summary
  $('ct-blk-count').textContent='('+c.active_blockers+' active, '+c.resolved_blockers+' resolved)';
  let bH='';
  if(c.blocker_type&&c.blocker_type!=='default'&&c.blocker_type!=='none'){
    bH+='<div style="color:var(--red);font-weight:bold;margin-bottom:4px">ACTIVE: '+c.blocker_type.toUpperCase().replace(/_/g,' ')+'</div>';
    (c.blocker_options||[]).forEach((o,i)=>{bH+='<div style="color:'+(i===0?'var(--green)':'var(--dim)')+'">'+(i===0?'>>> ':'')+esc(S(o.option,35))+' ('+(o.eta_seconds||'?')+'s)'+' ['+esc(o.owner||'local')+']'+'<br><span style="color:var(--dim)">'+esc(S(o.detail||'',55))+'</span></div>'});
  }
  if(c.resolved_blockers>0)bH+='<div style="color:var(--green);margin-top:4px">'+c.resolved_blockers+' blockers resolved</div>';
  if(!bH)bH='<div style="color:var(--green)">No blockers</div>';
  $('ct-blockers').innerHTML=bH;
  // Decisions
  $('ct-dec-count').textContent='('+c.total_decisions+')';
  let decH='';(c.decisions||[]).slice(0,8).forEach(dc=>{
    const col2=dc.type==='lesson'?'var(--yellow)':dc.type==='blocker_resolved'?'var(--green)':'var(--blue)';
    decH+='<div style="padding:2px 0;border-bottom:1px solid var(--border)"><span style="color:'+col2+'">'+dc.icon+'</span> '+esc(S(dc.text,70))+'</div>';
  });$('ct-decisions').innerHTML=decH||'<div style="color:var(--dim)">No decisions yet</div>';
  // ROI bar + Lessons
  const rPct=c.roi_score||0;const rCol=rPct>=80?'g':rPct>=50?'y':'r';
  $('ct-roi-bar').innerHTML='<div class="bw"><span class="bl" style="min-width:84px">Maximum ROI</span><div class="bar"><div class="bf '+rCol+'" style="width:'+rPct+'%"></div></div><span class="bp">'+rPct+'% ('+c.roi_positive+'↑ '+c.roi_negative+'↓)</span></div>';
  $('ct-les-count').textContent='('+c.lessons_count+' lessons, ROI '+c.roi_trend+')';
  let lsH='';(c.lessons_recent||[]).forEach(l=>{lsH+='<div class="lesson">['+esc(l.category)+'] '+esc(S(l.text,70))+'</div>'});
  $('ct-lessons').innerHTML=lsH||'<div style="color:var(--dim)">No lessons</div>';
  ok++}catch(e){fail++;console.error('ct',e)}
 try{$('task').textContent=p.task||'idle';$('timer').textContent=st==='running'?el(p.started_at):st;$('timer').className='timer'+(st!=='running'?' idle':'');ok++}catch(e){fail++;console.error('hdr',e)}
 try{$('os').className='dot '+st;sb('ob',pct,'g');$('op').textContent=pct.toFixed(1)+'%';const ex=(d.session||{}).execution||{};const lp=parseFloat(ex.local_models||(st==='running'?100:0)),cp2=parseFloat(ex.cloud_session||0);sb('lb',lp,'b');sb('cb',cp2,'y');$('lp').textContent=lp.toFixed(1)+'%';$('cp').textContent=cp2.toFixed(1)+'%';sb('tb',ts.percent||0,'p');$('tp').textContent=(ts.percent||0).toFixed(1)+'%';$('todo-count').textContent='('+(ts.done||0)+'/'+(ts.total||0)+' done, '+(ts.open||0)+' open)';const roi=d.roi||{};$('roi').innerHTML=roi.kill_switch?'<span style="color:var(--red)">ROI KILL SWITCH ACTIVE</span>':'<span style="color:var(--green)">ROI: healthy</span>';ok++}catch(e){fail++;console.error('prog',e)}
 try{$('eta-pipeline').textContent='Pipeline: '+(etas.pipeline_eta_display||'--')+' ('+(etas.remaining_roles||0)+' roles left)';$('eta-todo').textContent='All tasks: '+(etas.todo_eta_display||'--')+' ('+(etas.open_tasks||0)+' open)';const bO=br.options||[];$('eta-blockers').textContent='Blocker fix: '+(bO.length&&br.type!=='default'&&br.type!=='none'?(bO[0].eta_seconds||10)+'s (auto: '+S(bO[0].option,30)+')':'no active blockers');const ar=d.auto_remediation||{};$('auto-remediation').textContent=ui.auto_remediation_panel?'Auto-remediation: '+(ar.message||'idle'):'Auto-remediation: legacy mode';$('blocker-wait').textContent=ui.auto_remediation_panel?'Wait budget: '+(ar.chosen&&ar.chosen.eta_seconds?ar.chosen.eta_seconds+'s':'--'):'Wait budget: --';ok++}catch(e){fail++;console.error('eta',e)}
 try{const ops=d.ops_summary||[];let oH='';ops.forEach(item=>{oH+='<div><div style="display:flex;justify-content:space-between;font-size:11px"><span>'+esc(item.label||'')+'</span><span>'+Number(item.percent||0).toFixed(1)+'%</span></div><div class="bar" style="margin-top:2px"><div class="bf '+(item.color||'g')+'" style="width:'+(item.percent||0)+'%"></div></div><div class="mini-meta">'+esc((item.detail||'')+' • '+(item.subtitle||''))+'</div></div>'});$('ops-summary').innerHTML=oH||'<div style="color:var(--dim)">No ROI summary</div>';ok++}catch(e){fail++;console.error('ops',e)}
 try{const t=d.teaching||{};const cats=t.categories||{};const catLine=Object.entries(cats).map(([k,v])=>esc(k)+': '+v).join(' • ');$('teaching-summary').innerHTML='<div style="font-size:12px"><b>Current stage:</b> '+esc(t.current_stage||'none')+'</div><div style="font-size:12px;margin-top:4px"><b>Lessons:</b> '+(t.total_lessons||0)+' | <b>Applied:</b> '+(t.applied_total||0)+' | <b>Applicable now:</b> '+(t.applicable_count||0)+'</div><div style="font-size:11px;color:var(--dim);margin-top:4px">'+esc(catLine||'No lesson categories yet')+'</div>'+(t.next_fix?'<div style="font-size:11px;color:var(--green);margin-top:6px"><b>Next fix:</b> '+esc(S(t.next_fix,120))+'</div>':'');let ta='';(t.applicable||[]).forEach(item=>{ta+='<div class=\"lesson\">['+esc(item.category||'')+'] '+esc(S(item.lesson||'',90))+'<br><span style=\"color:var(--green)\">Fix:</span> '+esc(S(item.fix||'',90))+' <span style=\"color:var(--dim)\">| applied '+(item.applied_count||0)+'x</span></div>'});$('teaching-applicable').innerHTML=ta||'<div style=\"color:var(--dim)\">No stage-specific lessons active</div>';ok++}catch(e){fail++;console.error('teach',e)}
 try{if(ui.governance_panel){const gv=d.governance||{};const checks=(gv.required_checks||[]).length?(gv.required_checks||[]).map(c=>'<div style="font-size:10px;color:var(--dim)">• '+esc(c)+'</div>').join(''):'<div style="font-size:10px;color:var(--dim)">No required checks reported</div>';const color=gv.protected?'var(--green)':(gv.status==='blocked_by_plan'?'var(--yellow)':'var(--red)');$('governance-status').innerHTML='<div style="font-weight:bold;color:'+color+'">'+esc((gv.status||'unknown').toUpperCase())+'</div><div style="margin-top:4px">'+esc((gv.repo||'repo')+' / '+(gv.branch||'main')+' / '+(gv.visibility||'unknown'))+'</div><div style="margin-top:4px;color:var(--dim)">'+esc(gv.blocker||'Branch protection healthy.')+'</div><div style="margin-top:6px">'+checks+'</div><div style="margin-top:6px;font-size:10px;color:var(--dim)">Checked: '+esc(gv.checked_at||'--')+'</div>';}ok++}catch(e){fail++;console.error('gov',e)}
 try{const rs=d.resource||{},cpu=parseFloat(rs.cpu_percent||0),mem=parseFloat(rs.memory_percent||0);sb('cpub',cpu,bc(cpu));sb('memb',mem,bc(mem));$('cpup').textContent=cpu.toFixed(1)+'%';$('memp').textContent=mem.toFixed(1)+'%';ok++}catch(e){fail++;console.error('res',e)}
 try{const team=(d.runtime||{}).team||{},provs={};stages.forEach(s=>{if(s.id==='preflight')return;let pr='ollama';const dt=s.detail||'';if(dt.includes('github_models'))pr='github_models';else if(dt.includes('clawbot'))pr='clawbot';else if(dt.includes('openclaw'))pr='openclaw';if(!provs[pr])provs[pr]={t:0,c:0,m:new Set()};provs[pr].t++;if(s.status==='completed')provs[pr].c++;provs[pr].m.add((team[s.id]||{}).model||'?')});const tt=Object.values(provs).reduce((a,v)=>a+v.t,0)||1;let mH='<table><tr><th>Provider</th><th>%</th><th>Models</th><th>Done</th></tr>';Object.entries(provs).sort().forEach(([n,v])=>{const pp=(v.t/tt*100).toFixed(0);const tg=n==='ollama'?'local':'cloud';mH+='<tr><td><span class="tag '+tg+'">'+n+'</span></td><td>'+pp+'%</td><td style="font-size:10px">'+[...v.m].join(', ')+'</td><td>'+v.c+'/'+v.t+'</td></tr>'});mH+='</table>';$('mu').innerHTML=mH;ok++}catch(e){fail++;console.error('mu',e)}
 try{const sess=d.sessions||[];let sH='';if(sess.length){sess.forEach(s=>{const tg=(s.type||'').replace('local-','');sH+='<div class="sess"><span class="dot '+(s.status||'active')+'"></span><span class="tag '+tg+'">'+esc(s.type)+'</span><span>'+esc(S(s.detail,60))+'</span></div>'})}else{sH='<div style="color:var(--dim)">No active sessions</div>'}$('sessions').innerHTML=sH;ok++}catch(e){fail++;console.error('sess',e)}
 try{const acts=d.local_agent_activity||[];let aH='';if(acts.length){acts.forEach(a=>{const dot=a.status==='running'?'running':a.status==='completed'?'completed':a.status==='failed'?'failed':'pending';const icon=a.status==='running'?'▶':a.status==='completed'?'✓':a.status==='failed'?'✗':'○';const files=(a.files||[]).length?' ['+a.files.slice(0,2).join(', ')+']':'';const model=a.model?' ('+a.model+')':'';aH+='<div style="font-size:11px;padding:4px 0;border-bottom:1px solid var(--border)"><span class="dot '+dot+'"></span><b>'+esc(a.label||a.role)+'</b> '+icon+' '+esc(S(a.detail,60))+model+files+'<div class="bar" style="height:6px;margin-top:2px"><div class="bf g" style="width:'+(a.percent||0)+'%"></div></div></div>'})}else{aH='<div style="color:var(--dim)">No local agents active</div>'}$('agent-activity').innerHTML=aH;ok++}catch(e){fail++;console.error('act',e)}
 try{const co=d.coordination||{},cl=co.claims||[],col=co.collisions||[];let cH='';if(cl.length){cl.forEach(c=>{cH+='<div style="font-size:11px"><span class="tag agent">'+esc(c.role)+'</span> '+(c.files||[]).slice(0,3).join(', ')+'</div>'})}else{cH='<div style="color:var(--dim)">No file claims</div>'}if(col.length){col.slice(-3).forEach(c=>{cH+='<div class="collision">'+esc(c.file)+' — '+esc(c.claimed_by)+' vs '+esc(c.requested_by)+'</div>'})}$('coord').innerHTML=cH;ok++}catch(e){fail++;console.error('coord',e)}
 try{if($('session-matrix')){const sm=d.session_matrix||[];let smH='';if(sm.length){smH+='<table><tr><th>Owner</th><th>Work</th><th>ETA</th></tr>';sm.forEach(s=>{smH+='<tr><td>'+esc(s.owner)+'</td><td>'+esc(S(s.assigned_work,36))+'</td><td>'+esc(s.eta_display||'--')+'</td></tr>'});smH+='</table>'}else{smH='<div style="color:var(--dim)">No session matrix</div>'}$('session-matrix').innerHTML=smH}ok++}catch(e){fail++;console.error('sm',e)}
 try{const sbd=d.session_board||[];$('session-board-count').textContent='('+sbd.filter(s=>s.active).length+' active / '+sbd.length+' lanes)';let sbH='';sbd.forEach(s=>{const tag=(s.id||'').replace('local-agent','local')||'agent';const sd2=s.active?'active':'pending';const opts=(s.options||[]).map((o,i)=>'<div style="font-size:10px;margin-top:2px;color:'+(i===0?'var(--green)':'var(--dim)')+'">'+(i===0?'>>> ':'')+esc(S(o.option,40))+' | '+(o.eta_seconds||'?')+'s</div>').join('');sbH+='<div style="background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:8px"><div style="display:flex;justify-content:space-between;align-items:center"><div><span class="tag '+tag+'">'+esc(s.label||s.id)+'</span> <span class="dot '+sd2+'"></span></div><div style="color:var(--yellow);font-size:12px;font-weight:bold">ETA: '+esc(s.eta_display||'--')+'</div></div><div style="margin-top:6px;font-size:12px">'+esc(S(s.assigned_work||'idle',110))+'</div><div style="margin-top:3px;color:var(--dim);font-size:10px">'+esc(S(s.detail,80)||'idle')+'</div>'+(opts?'<div style="margin-top:6px;padding-top:4px;border-top:1px solid var(--border)"><div style="font-size:10px;color:var(--dim)">Deadline: '+(s.decision_deadline_seconds||10)+'s</div>'+opts+'</div>':'')+'</div>'});$('session-board').innerHTML=sbH||'<div style="color:var(--dim)">No session lanes</div>';ok++}catch(e){fail++;console.error('sboard',e)}
 try{if(ui.executive_conflict){const neg=d.executive_negotiation||[];let nH='';neg.forEach(item=>{const tn=parseFloat(item.tension||0);const col=tn>=90?'var(--red)':tn>=75?'var(--yellow)':'var(--blue)';nH+='<div style="background:#181d24;border:1px solid '+col+';border-radius:6px;padding:8px;box-shadow:inset 0 0 0 1px rgba(255,255,255,0.03)"><div style="display:flex;justify-content:space-between;gap:8px"><div style="font-weight:bold;color:'+col+';margin-bottom:4px">'+esc(item.title||'')+'</div><div style="font-size:10px;color:'+col+'">Tension '+tn.toFixed(0)+'%</div></div><div style="font-size:10px;color:var(--red);margin-bottom:6px">'+esc(S(item.fight||'',120))+'</div><div style="font-size:11px;color:var(--blue)">Left: '+esc(S(item.left||'',90))+'</div><div style="font-size:11px;color:var(--purple);margin-top:4px">Right: '+esc(S(item.right||'',90))+'</div><div style="display:flex;justify-content:space-between;gap:8px;margin-top:6px;font-size:10px"><span style="color:var(--green)">Winner: '+esc(item.winner||'')+'</span><span style="color:var(--red)">Loser: '+esc(item.loser||'')+'</span></div><div style="margin-top:6px;padding-top:4px;border-top:1px solid var(--border);font-size:10px;color:var(--yellow)">Forced decision: '+esc(S(item.decision||'',120))+'</div></div>'});$('executive-negotiation').innerHTML=nH||'<div style="color:var(--dim)">No active executive tension</div>';}ok++}catch(e){fail++;console.error('neg',e)}
 try{if($('project-rollups')){const pb=d.project_board||{};const cards=(pb.lanes||[]).concat(pb.use_cases||[]).map(item=>'<div class="mini-card"><div class="mini-title">'+esc(item.label)+'</div><div class="mini-metric">'+Number(item.percent||0).toFixed(1)+'%</div><div class="mini-meta">'+(item.done||0)+'/'+(item.total||0)+' done</div></div>');if($('project-rollups'))$('project-rollups').innerHTML=cards.join('')||'<div style="color:var(--dim)">No rollups</div>'}ok++}catch(e){fail++;console.error('rollups',e)}
 try{$('role-count').textContent='('+stages.filter(s=>s.status==='completed').length+'/'+stages.length+' done)';let rH='';stages.forEach(s=>{const sp=s.percent||0,ss=s.status||'pending';rH+='<div class="bw" title="'+esc(s.detail)+'"><span class="bl"><span class="dot '+ss+'"></span>'+(s.label||s.id)+'</span><div class="bar"><div class="bf g" style="width:'+sp+'%"></div></div><span class="bp">'+sp.toFixed(0)+'%</span></div>'});$('roles').innerHTML=rH||'<div style="color:var(--dim)">No roles</div>';ok++}catch(e){fail++;console.error('roles',e)}
 try{const blockers=td.blockers||[];$('blocker-count').textContent='('+blockers.length+')';if(blockers.length){let bkH='';if(br.type&&br.type!=='default'&&br.type!=='none'){bkH+='<div style="background:#2d1517;padding:6px;border-radius:4px;margin-bottom:6px"><span style="color:var(--red);font-weight:bold">ACTIVE: '+br.type.toUpperCase().replace(/_/g,' ')+'</span>';(br.options||[]).forEach((o,i)=>{bkH+='<div style="font-size:10px;margin-top:2px;color:'+(i===0?'var(--green)':'var(--dim)')+'">'+(i===0?'>>> ':'    ')+'Option '+(i+1)+': '+esc(S(o.option,40))+' ('+(o.eta_seconds||'?')+'s)</div>'});bkH+='</div>'}bkH+=blockers.map(b=>'<div class="item blocker">'+esc(S(b.text,120))+'<br><small>'+esc(b.section||'')+'</small></div>').join('');$('blockers').innerHTML=bkH}else{$('blockers').innerHTML='<div style="color:var(--green)">No blockers!</div>'}ok++}catch(e){fail++;console.error('blk',e)}
 try{const working=td.working||[];$('working-count').textContent='('+working.length+')';$('working').innerHTML=working.length?working.map(w=>'<div class="item working">'+esc(S(w.text,120))+'<br><small>'+esc(w.section||'')+'</small></div>').join(''):'<div style="color:var(--dim)">Nothing in progress</div>';ok++}catch(e){fail++;console.error('work',e)}
 try{const doneItems=(td.items||[]).filter(i=>i.done);$('done-count').textContent='('+doneItems.length+')';$('done-items').innerHTML=doneItems.length?doneItems.slice(-15).map(i=>'<div class="item done">'+esc(S(i.text,100))+'</div>').join(''):'<div style="color:var(--dim)">None yet</div>';ok++}catch(e){fail++;console.error('done',e)}
 try{const allItems=td.items||[];let curSec='',todoHtml='';allItems.forEach(i=>{if(i.section!==curSec){curSec=i.section;todoHtml+='<div style="color:var(--blue);margin-top:6px;font-weight:bold">'+esc(curSec)+'</div>'}const cls=i.done?'item done':'item open';const icon=i.done?'✓':'○';todoHtml+='<div class="'+cls+'"><span>'+icon+'</span> '+esc(S(i.text,150))+'</div>'});$('todo-list').innerHTML=todoHtml||'<div style="color:var(--dim)">No items</div>';ok++}catch(e){fail++;console.error('todo',e)}
 try{const les=d.lessons||[];$('lesson-count').textContent='('+les.length+')';$('lessons').innerHTML=les.length?les.slice(-8).map(l=>'<div class="lesson">['+esc(l.category||'')+'] '+esc(S(l.lesson,100))+'</div>').join(''):'<div style="color:var(--dim)">No lessons yet</div>';ok++}catch(e){fail++;console.error('les',e)}
 try{
  const c=d.completion||{};
  const topCard='<div style="background:#1c2128;border:1px solid var(--border);border-radius:6px;padding:8px">'+
    '<div style="display:flex;justify-content:space-between;font-size:12px"><b>All Tasks</b><span>'+Number(c.overall_percent||0).toFixed(1)+'%</span></div>'+
    '<div class="bar" style="margin-top:4px"><div class="bf p" style="width:'+(c.overall_percent||0)+'%"></div></div>'+
    '<div class="mini-meta">ETA '+esc(c.todo_eta||'--')+' • '+(c.open_tasks||0)+' open • ROI '+(c.roi_score||0)+'%</div>'+
  '</div>';
  const blockerItems=(c.blocker_options||[]).length
    ? (c.blocker_options||[]).map((b,i)=>'<div class="item blocker">'+(i===0?'>>> ':'')+esc(S(b.option||'',50))+'<br><small>'+esc((b.eta_seconds||'?')+'s • '+S(b.detail||'',60))+'</small></div>').join('')
    : '<div style="color:var(--green)">No active blockers</div>';
  const blockerCard='<div style="background:#1c2128;border:1px solid var(--border);border-radius:6px;padding:8px">'+
    '<div style="font-weight:bold;font-size:12px;margin-bottom:4px">Blockers Faced</div>'+blockerItems+
  '</div>';
  const decisionItems=(c.decisions||[]).slice(0,5).map(d2=>'<div class="item working"><span>'+esc(d2.icon||'•')+'</span> '+esc(S(d2.text||'',80))+'</div>').join('');
  const lessonItems=(c.lessons_recent||[]).slice(0,4).map(l=>'<div class="lesson">['+esc(l.category||'')+'] '+esc(S(l.text||'',80))+'</div>').join('');
  const decisionCard='<div style="background:#1c2128;border:1px solid var(--border);border-radius:6px;padding:8px">'+
    '<div style="font-weight:bold;font-size:12px;margin-bottom:4px">Decisions + Lessons</div>'+
    (decisionItems||'<div style="color:var(--dim)">No decisions yet</div>')+
    lessonItems+
  '</div>';
  $('completion-forecast').innerHTML=topCard+blockerCard+decisionCard;
  ok++
 }catch(e){fail++;console.error('completion',e)}
 try{const tl=d.timeline||[];$('timeline').innerHTML=tl.length?tl.slice(-12).reverse().map(e=>{const t=(e.timestamp||'').split('T')[1]||'';return '<div class="tl-item"><span class="time">'+t+'</span><span class="role">'+esc(e.role||'')+'</span><span class="msg">'+esc(S(e.content,60))+'</span></div>'}).join(''):'<div style="color:var(--dim)">No events</div>';ok++}catch(e){fail++;console.error('tl',e)}
 try{const flow=d.task_flow||{},nodes=flow.nodes||[];let fH='';if(nodes.length){nodes.forEach((n,i)=>{const sc=n.status==='completed'?'var(--green)':n.status==='running'?'var(--blue)':n.status==='blocked'?'var(--red)':'var(--border)';fH+='<div style="min-width:140px;background:#1c2128;border:2px solid '+sc+';border-radius:6px;padding:8px"><div style="font-size:10px;color:var(--dim)">STEP '+(i+1)+'</div><div style="font-size:11px;margin-top:3px;font-weight:bold">'+esc(n.label||n.id||'')+'</div><div style="font-size:10px;color:var(--dim);margin-top:2px">'+esc(n.owner||'')+'</div><div style="font-size:10px;color:var(--yellow);margin-top:2px">'+esc(n.eta||'')+'</div></div>';if(i<nodes.length-1)fH+='<div style="align-self:center;color:var(--blue);font-size:18px;padding:0 4px">→</div>'})}else{fH='<div style="color:var(--dim)">No task flow</div>'}$('task-flow').innerHTML=fH;ok++}catch(e){fail++;console.error('flow',e)}
 $('refresh').textContent='Last: '+new Date().toLocaleTimeString()+' | 2s | '+ok+' OK'+(fail?' | '+fail+' ERR':'');
}
R();setInterval(R,2000);
