#!/usr/bin/env python3
"""
deploy.py — Deploy local agents to any project.

Makes each specialized agent available as a standalone Python module
that works on a target project's codebase. Zero coupling to this repo.

Usage:
    python3 deploy.py --list                         list all agents
    python3 deploy.py executor --to /path/to/project deploy executor to project
    python3 deploy.py all --to /path/to/project      deploy all agents
    python3 deploy.py executor --run "Write LRU Cache" --to /path/to/project
    python3 deploy.py --status /path/to/project      show deployed agents

What gets deployed:
    <project>/.local-agents/
        agents/           — specialized agent modules (read-only copies)
        subagent_pool.py  — parallel worker pool
        runner.py         — single entry point: runner.run_task(task)
        config.yaml       — agent config (model, timeout, budget)
        registry.json     — version + benchmark scores
"""
import os, sys, json, shutil, argparse
from pathlib import Path
from datetime import datetime

HERE = Path(__file__).parent
AGENTS_DIR = HERE / "agents"
DEPLOY_DIR_NAME = ".local-agents"


def list_agents():
    agents = []
    for f in sorted(AGENTS_DIR.glob("*.py")):
        if f.name.startswith("_") or f.name == "config.yaml":
            continue
        agents.append(f.stem)
    return agents


def deploy(agent_names: list, target: str):
    target_path = Path(target).resolve()
    deploy_path = target_path / DEPLOY_DIR_NAME

    # Create deploy dir structure
    (deploy_path / "agents").mkdir(parents=True, exist_ok=True)

    # Copy agent files
    deployed = []
    for name in agent_names:
        src = AGENTS_DIR / f"{name}.py"
        if not src.exists():
            print(f"  SKIP: {name} (not found)")
            continue
        dst = deploy_path / "agents" / f"{name}.py"
        shutil.copy2(src, dst)
        deployed.append(name)
        print(f"  + {name} -> {dst}")

    # Copy subagent pool
    pool_src = AGENTS_DIR / "subagent_pool.py"
    if pool_src.exists():
        shutil.copy2(pool_src, deploy_path / "agents" / "subagent_pool.py")

    # Copy agent_runner.py — core Nexus engine loop required by executor
    runner_src = HERE / "agent_runner.py"
    if runner_src.exists():
        shutil.copy2(runner_src, deploy_path / "agent_runner.py")

    # Copy __init__.py (router)
    init_src = AGENTS_DIR / "__init__.py"
    if init_src.exists():
        shutil.copy2(init_src, deploy_path / "agents" / "__init__.py")

    # Write runner.py — project-local entry point
    runner_content = f'''#!/usr/bin/env python3
"""
runner.py — Local agent entry point for this project.
Generated by local-agents deploy.py on {datetime.now().strftime("%Y-%m-%d")}.

Usage:
    from .local-agents.runner import run_task
    result = run_task({{"title": "...", "description": "...", "category": "code_gen"}})

Or from CLI:
    python3 .local-agents/runner.py "Write a binary search function"
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

# Set codebase path to this project
os.environ.setdefault("LOCAL_AGENT_TARGET_REPO", "{target_path}")
_bos_default = "{target_path}/.local-agents/work"
_bos = os.environ.get("BOS_HOME", _bos_default)
# Guard against broken symlinks (resolves to non-existent target)
if os.path.islink(_bos) and not os.path.exists(os.path.realpath(_bos)):
    _bos = _bos_default
os.environ["BOS_HOME"] = _bos
try:
    os.makedirs(_bos, exist_ok=True)
except OSError:
    os.environ["BOS_HOME"] = _bos_default
    os.makedirs(_bos_default, exist_ok=True)

from agents import run_task, route, list_agents


def run(task_or_description, category: str = "code_gen") -> dict:
    """
    Run a task on this project.

    Args:
        task_or_description: task dict OR plain string description
        category: code_gen | bug_fix | tdd | scaffold | refactor | arch | research | doc
    """
    if isinstance(task_or_description, str):
        task = {{"id": 1, "title": task_or_description[:80],
                 "description": task_or_description,
                 "category": category,
                 "codebase_path": "{target_path}"}}
    else:
        task = task_or_description
        task.setdefault("codebase_path", "{target_path}")
    return run_task(task)


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="Local Agent Runner")
    ap.add_argument("task", nargs="?", default="", help="Task description")
    ap.add_argument("--category", default="code_gen", help="Task category")
    ap.add_argument("--list", action="store_true", help="List available agents")
    args = ap.parse_args()

    if args.list:
        print("Available agents:", ", ".join(list_agents()))
    elif args.task:
        result = run(args.task, args.category)
        print(f"Status:  {{result.get('status')}}")
        print(f"Quality: {{result.get('quality', 0)}}/100")
        print(f"Agent:   {{result.get('agent', route({{'category': args.category}}))}} ")
        if result.get("output"):
            print(f"Output:\\n{{result['output'][:500]}}")
    else:
        ap.print_help()
'''
    (deploy_path / "runner.py").write_text(runner_content)

    # Write config.yaml
    config_src = HERE / "agents" / "config.yaml"
    if config_src.exists():
        shutil.copy2(config_src, deploy_path / "config.yaml")

    # Write registry.json
    registry_src = HERE / "registry" / "agents.json"
    if registry_src.exists():
        shutil.copy2(registry_src, deploy_path / "registry.json")

    # Write .gitignore for work dir
    (deploy_path / ".gitignore").write_text("work/\n*.pyc\n__pycache__/\n")

    # Write deploy manifest
    manifest = {
        "deployed_at": datetime.now().isoformat(),
        "source": str(HERE),
        "target": str(target_path),
        "agents": deployed,
        "nexus_model": "nexus-local",
        "claude_rescue_budget": "10%",
    }
    (deploy_path / "manifest.json").write_text(json.dumps(manifest, indent=2))

    print(f"\nDeployed {len(deployed)} agent(s) to {deploy_path}")
    print(f"Entry point: python3 {deploy_path}/runner.py \"<task>\"")
    return deployed


def show_status(target: str):
    deploy_path = Path(target).resolve() / DEPLOY_DIR_NAME
    manifest_path = deploy_path / "manifest.json"
    if not manifest_path.exists():
        print(f"No agents deployed to {target}")
        return
    manifest = json.loads(manifest_path.read_text())
    print(f"Deployed agents at {deploy_path}:")
    for a in manifest.get("agents", []):
        print(f"  - {a}")
    print(f"Deployed at: {manifest.get('deployed_at', 'unknown')}")
    print(f"Source:      {manifest.get('source', 'unknown')}")


def main():
    ap = argparse.ArgumentParser(description="Deploy local agents to any project")
    ap.add_argument("agent", nargs="?", default="", help="Agent name or 'all'")
    ap.add_argument("--to", default="", metavar="PROJECT_PATH", help="Target project directory")
    ap.add_argument("--list", action="store_true", help="List available agents")
    ap.add_argument("--status", metavar="PROJECT_PATH", help="Show deployed agents in project")
    ap.add_argument("--run", metavar="TASK", help="Deploy and immediately run a task")
    args = ap.parse_args()

    if args.list:
        print("Available agents:")
        for a in list_agents():
            print(f"  {a}")
        return

    if args.status:
        show_status(args.status)
        return

    if not args.to:
        print("Error: --to <project_path> required")
        ap.print_help()
        sys.exit(1)

    agent_names = list_agents() if args.agent == "all" else [args.agent] if args.agent else list_agents()
    deployed = deploy(agent_names, args.to)

    if args.run and deployed:
        deploy_path = Path(args.to).resolve() / DEPLOY_DIR_NAME
        os.system(f'python3 "{deploy_path}/runner.py" "{args.run}"')


if __name__ == "__main__":
    main()
