#!/bin/bash
# Auto‑generate role definitions from a YAML org structure.
#
# This script reads a simple YAML file (state/org_structure.yaml) that
# describes the roles and reporting structure of your company.  It
# creates a Markdown file under the roles/ directory for each role if
# one does not already exist.  The generated roles focus on
# revenue‑generating responsibilities and specify that every activity
# should be tied to an outcome that benefits the business.

# Path to the org structure file.  You can edit or replace this file
# with your own organisational hierarchy.
ORG_FILE="$(dirname "$0")/../state/org_structure.yaml"
ROLES_DIR="$(dirname "$0")/../roles"

if [ ! -f "$ORG_FILE" ]; then
  echo "role_generator: no org structure found at $ORG_FILE" >&2
  exit 0
fi

mkdir -p "$ROLES_DIR"

# Extract role names and descriptions from the YAML file.  The YAML
# should have the following structure:
#
# roles:
#   - name: CEO
#     description: Chief Executive Officer of the company
#   - name: CFO
#     description: Chief Financial Officer
#   - name: Engineer
#     description: Software engineer
#
# This parser is intentionally simple; it only supports top‑level
# "roles" entries with "name" and optional "description" keys.

current_role=""
current_desc=""
while IFS= read -r line; do
  # Trim leading and trailing whitespace
  trimmed="${line##*# }"
  # Start of a new role entry
  if [[ "$line" =~ ^[[:space:]]*-?[[:space:]]*name:[[:space:]]*(.+)$ ]]; then
    # Write out the previous role if we captured one
    if [ -n "$current_role" ]; then
      role_file="$ROLES_DIR/$(echo "$current_role" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr '/' '-')-role.md"
      if [ ! -f "$role_file" ]; then
        echo "Generating role definition: $role_file"
        cat > "$role_file" <<EOF_ROLE
# ${current_role} Role

**Purpose:** ${current_desc:-"Auto‑generated role based on the organisational structure."}

**Responsibilities:**
- Align all activities with revenue generation and positive business outcomes.
- Minimise unnecessary work and cost; focus on tasks that directly contribute to growth and profitability.
- Continuously learn from successes and failures, updating skills and workflows accordingly.

**Success metrics:**
- Positive contribution to the profit and loss (P&L) ledger.
- Efficiency: minimal resource consumption (CPU, memory, time) relative to delivered value.
- Impact: measurable improvements in revenue or cost savings.

**Notes:**
This role was automatically generated by the local agent framework based on the org structure.  You can customise the responsibilities, success metrics and purpose to better reflect your business.
EOF_ROLE
      fi
    fi
    current_role="${BASH_REMATCH[1]}"
    current_desc=""
  elif [[ "$line" =~ ^[[:space:]]*description:[[:space:]]*(.+)$ ]]; then
    current_desc="${BASH_REMATCH[1]}"
  fi
done < "$ORG_FILE"

# Write the last role
if [ -n "$current_role" ]; then
  role_file="$ROLES_DIR/$(echo "$current_role" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr '/' '-')-role.md"
  if [ ! -f "$role_file" ]; then
    echo "Generating role definition: $role_file"
    cat > "$role_file" <<EOF_ROLE
# ${current_role} Role

**Purpose:** ${current_desc:-"Auto‑generated role based on the organisational structure."}

**Responsibilities:**
- Align all activities with revenue generation and positive business outcomes.
- Minimise unnecessary work and cost; focus on tasks that directly contribute to growth and profitability.
- Continuously learn from successes and failures, updating skills and workflows accordingly.

**Success metrics:**
- Positive contribution to the profit and loss (P&L) ledger.
- Efficiency: minimal resource consumption (CPU, memory, time) relative to delivered value.
- Impact: measurable improvements in revenue or cost savings.

**Notes:**
This role was automatically generated by the local agent framework based on the org structure.  You can customise the responsibilities, success metrics and purpose to better reflect your business.
EOF_ROLE
  fi
fi

echo "role_generator: complete.  Review generated role files in $ROLES_DIR." >&2
exit 0